
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin/"
      - "/Users/vladistone/.local/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/vladistone/.cargo/bin/"
      - "/opt/homebrew/Caskroom/miniforge/base/bin/"
      - "/opt/homebrew/Caskroom/miniforge/base/condabin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/vladistone/bin/"
      - "/Users/vladistone/.fzf/bin/"
    searched_directories:
      - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin/uname"
      - "/Users/vladistone/.local/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Users/vladistone/.cargo/bin/uname"
      - "/opt/homebrew/Caskroom/miniforge/base/bin/uname"
      - "/opt/homebrew/Caskroom/miniforge/base/condabin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin"
        - "/Users/vladistone/.local/share/../bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/vladistone/.cargo/bin"
        - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin"
        - "/Users/vladistone/.local/bin"
        - "/opt/homebrew/Caskroom/miniforge/base/bin"
        - "/opt/homebrew/Caskroom/miniforge/base/condabin"
        - "/Users/vladistone/.local/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/vladistone/bin"
        - "/Users/vladistone/.fzf/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:218 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 24.6.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:66 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin/"
      - "/Users/vladistone/.local/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/vladistone/.cargo/bin/"
      - "/opt/homebrew/Caskroom/miniforge/base/bin/"
      - "/opt/homebrew/Caskroom/miniforge/base/condabin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/Library/Apple/usr/bin/"
      - "/Users/vladistone/bin/"
      - "/Users/vladistone/.fzf/bin/"
    searched_directories:
      - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin/install_name_tool"
      - "/Users/vladistone/.local/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/Users/vladistone/.cargo/bin/install_name_tool"
      - "/opt/homebrew/Caskroom/miniforge/base/bin/install_name_tool"
      - "/opt/homebrew/Caskroom/miniforge/base/condabin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin"
        - "/Users/vladistone/.local/share/../bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/vladistone/.cargo/bin"
        - "/Users/vladistone/Library/Arduino15/packages/teensy/tools/teensy-compile/15.2.1/avr/bin"
        - "/Users/vladistone/.local/bin"
        - "/opt/homebrew/Caskroom/miniforge/base/bin"
        - "/opt/homebrew/Caskroom/miniforge/base/condabin"
        - "/Users/vladistone/.local/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/Library/Apple/usr/bin"
        - "/Users/vladistone/bin"
        - "/Users/vladistone/.fzf/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
